"""
Dead Code Elimination (DCE) Optimization Pass for the Luna compiler.

DCE removes instructions whose results are never used. This cleans up
code generated by other optimizations and reduces the final program size.

The algorithm:
1. Build a set of all values that are "live" (used somewhere)
2. Remove instructions that define values that aren't live
3. Be careful not to remove instructions with side effects (calls, returns)

Examples:
    x = 5        ; dead if x not used later
    y = x + 1    ; dead if y not used
    z = y * 2
    return z     ; z is live, so y is live, but x might still be dead

The pass handles:
- Removing unused LoadConst
- Removing unused BinaryOp/UnaryOp
- Removing unused Copy
- Preserving side-effecting instructions (Call, Return, Branch, Jump)
- Handling phi functions
"""

from typing import Set
from src.ir.instructions import (
    IRFunction,
    BasicBlock,
    IRInstruction,
    BinaryOp,
    UnaryOp,
    Copy,
    LoadConst,
    Phi,
    Call,
    Return,
    Branch,
    Jump,
    IRValue,
)
from src.ir.optimizations.pass_manager import FunctionPass, PassStatistics


class DeadCodeElimination(FunctionPass):
    """
    Dead code elimination optimization pass.

    Removes instructions whose results are never used.
    """

    @property
    def name(self) -> str:
        return "DeadCodeElimination"

    def optimize(self, func: IRFunction) -> PassStatistics:
        """
        Run DCE on a function.

        Uses a simple mark-and-sweep algorithm:
        1. Mark all values that are used
        2. Remove instructions that define unused values

        Args:
            func: The function to optimize (modified in place)

        Returns:
            Statistics about changes made
        """
        stats = PassStatistics(pass_name=self.name)

        # Keep iterating until no more changes
        # (removing dead code might make other code dead)
        changed = True
        while changed:
            changed = False

            # Find all live values
            live_values = self._find_live_values(func)

            # Remove dead instructions
            for block in func.blocks.values():
                to_remove = []

                for i, instr in enumerate(block.instructions):
                    if self._is_dead(instr, live_values):
                        to_remove.append(i)
                        changed = True

                # Remove in reverse order to maintain indices
                for i in reversed(to_remove):
                    del block.instructions[i]
                    stats.instructions_removed += 1

        return stats

    def _find_live_values(self, func: IRFunction) -> Set[IRValue]:
        """
        Find all values that are used (live) in the function.

        A value is live if:
        - It's used by a Return instruction
        - It's used by a Branch instruction
        - It's used by a Call instruction
        - It's used by another instruction that defines a live value

        Returns:
            Set of live IRValues
        """
        live: Set[IRValue] = set()
        worklist: Set[IRValue] = set()

        # First pass: find directly live values
        # (used by terminators and calls)
        for block in func.blocks.values():
            for instr in block.instructions:
                if isinstance(instr, Return):
                    if instr.value is not None:
                        worklist.add(instr.value)
                elif isinstance(instr, Branch):
                    worklist.add(instr.condition)
                elif isinstance(instr, Call):
                    # Function calls have side effects, so all args are live
                    for arg in instr.arguments:
                        worklist.add(arg)
                    # The call itself might return a value that's live
                    # (handled by other instructions using it)

        # Propagate liveness backwards
        while worklist:
            value = worklist.pop()
            if value in live:
                continue

            live.add(value)

            # Find the instruction that defines this value
            defining_instr = self._find_definition(func, value)
            if defining_instr is not None:
                # All uses of the defining instruction are now live
                for use in defining_instr.get_uses():
                    if use not in live:
                        worklist.add(use)

        return live

    def _find_definition(self, func: IRFunction, value: IRValue) -> IRInstruction:
        """
        Find the instruction that defines a value.

        Args:
            func: The function to search
            value: The value to find the definition for

        Returns:
            The defining instruction, or None if not found
        """
        if value.is_constant:
            return None

        for block in func.blocks.values():
            for instr in block.instructions:
                defined = instr.get_def()
                if defined is not None and defined == value:
                    return instr

        return None

    def _is_dead(self, instr: IRInstruction, live_values: Set[IRValue]) -> bool:
        """
        Check if an instruction is dead (can be removed).

        Args:
            instr: The instruction to check
            live_values: Set of values that are live

        Returns:
            True if the instruction is dead and can be removed
        """
        # Side-effecting instructions are never dead
        if isinstance(instr, (Return, Jump, Branch)):
            return False

        # Calls might have side effects even if result is unused
        if isinstance(instr, Call):
            return False

        # Check if the defined value is live
        defined = instr.get_def()
        if defined is None:
            return False

        return defined not in live_values
